export const resp = {
  quizID: 1,
  quizName: "solar-system-quiz",
  totalQuestions: 10,
  questions: [
    {
      questionId: "1",
      questionText: "What is the 6th planet in the solar system?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Planet+6",
      options: [
        { optionId: "1", optionText: "Jupiter" },
        { optionId: "2", optionText: "Saturn" },
        { optionId: "3", optionText: "Earth" },
        { optionId: "4", optionText: "Neptune" },
      ],
      correctOptionId: "2",
    },
    {
      questionId: "2",
      questionText: "Which planet is known as the Red Planet?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Red+Planet",
      options: [
        { optionId: "1", optionText: "Mars" },
        { optionId: "2", optionText: "Venus" },
        { optionId: "3", optionText: "Mercury" },
        { optionId: "4", optionText: "Jupiter" },
      ],
      correctOptionId: "1",
    },
    {
      questionId: "3",
      questionText: "What is the largest planet in the solar system?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Largest+Planet",
      options: [
        { optionId: "1", optionText: "Earth" },
        { optionId: "2", optionText: "Jupiter" },
        { optionId: "3", optionText: "Saturn" },
        { optionId: "4", optionText: "Neptune" },
      ],
      correctOptionId: "2",
    },
    {
      questionId: "4",
      questionText: "Which planet is closest to the Sun?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Closest+to+Sun",
      options: [
        { optionId: "1", optionText: "Mercury" },
        { optionId: "2", optionText: "Venus" },
        { optionId: "3", optionText: "Earth" },
        { optionId: "4", optionText: "Mars" },
      ],
      correctOptionId: "1",
    },
    {
      questionId: "5",
      questionText: "Which planet has the most moons?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Most+Moons",
      options: [
        { optionId: "1", optionText: "Saturn" },
        { optionId: "2", optionText: "Jupiter" },
        { optionId: "3", optionText: "Neptune" },
        { optionId: "4", optionText: "Uranus" },
      ],
      correctOptionId: "2",
    },
    {
      questionId: "6",
      questionText: "Which planet is known as Earth's twin?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Earth%27s+Twin",
      options: [
        { optionId: "1", optionText: "Mars" },
        { optionId: "2", optionText: "Venus" },
        { optionId: "3", optionText: "Mercury" },
        { optionId: "4", optionText: "Jupiter" },
      ],
      correctOptionId: "2",
    },
    {
      questionId: "7",
      questionText: "What is the smallest planet in the solar system?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Smallest+Planet",
      options: [
        { optionId: "1", optionText: "Mercury" },
        { optionId: "2", optionText: "Mars" },
        { optionId: "3", optionText: "Pluto" },
        { optionId: "4", optionText: "Venus" },
      ],
      correctOptionId: "1",
    },
    {
      questionId: "8",
      questionText: "Which planet has a day longer than its year?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Long+Day",
      options: [
        { optionId: "1", optionText: "Mercury" },
        { optionId: "2", optionText: "Venus" },
        { optionId: "3", optionText: "Earth" },
        { optionId: "4", optionText: "Mars" },
      ],
      correctOptionId: "2",
    },
    {
      questionId: "9",
      questionText: "What is the 7th planet in the solar system?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Planet+7",
      options: [
        { optionId: "1", optionText: "Uranus" },
        { optionId: "2", optionText: "Saturn" },
        { optionId: "3", optionText: "Jupiter" },
        { optionId: "4", optionText: "Neptune" },
      ],
      correctOptionId: "1",
    },
    {
      questionId: "10",
      questionText: "Which planet has rings?",
      imageUrl: "https://dummyimage.com/600x400/000/fff&text=Planet+with+Rings",
      options: [
        { optionId: "1", optionText: "Saturn" },
        { optionId: "2", optionText: "Jupiter" },
        { optionId: "3", optionText: "Neptune" },
        { optionId: "4", optionText: "All of the above" },
      ],
      correctOptionId: "4",
    },
  ],
};
